import { Link } from '@inertiajs/react';
import { ArrowRight, ChevronLeft, ChevronRight, Search, Sparkles } from 'lucide-react';
import SiteShell from '../Components/Common/SiteShell';
import { BookCard } from '../Components/Common/BookCard';
import { Book, MagazineEdition, LibraryStats, SmansaWork } from '../types/library';

interface HomeProps {
    stats: LibraryStats;
    popularBooks: Book[];
    latestMagazines: (MagazineEdition & { magazine?: { title: string; slug: string } })[];
    featuredWorks: SmansaWork[];
    settings: { library_name: string; library_tagline: string; operating_hours: string; library_address: string; contact_phone: string };
}

const featureCards = [
    { eyebrow: 'E-Katalog', title: 'Cari koleksi buku', description: 'Temukan buku berdasarkan judul, penulis, atau kategori.', href: '/catalog', color: 'bg-[#eef7fb]', icon: '⌕' },
    { eyebrow: 'E-Magazine', title: 'Baca digital', description: 'Nikmati majalah dan edisi pilihan kapan saja.', href: '/magazines', color: 'bg-[#fff5d9]', icon: '▤' },
    { eyebrow: 'Kontak', title: 'Hubungi pustaka', description: 'Tanyakan koleksi atau bantuan peminjaman.', href: '/contact', color: 'bg-[#fbece5]', icon: '✦' },
];

export default function Home({ stats = { total_books: 0, available_books: 0, total_authors: 0, total_categories: 0 }, popularBooks = [], latestMagazines = [] }: HomeProps) {
    return (
        <SiteShell>
            <div className="bg-[#fffdfa] text-[#172334]">
                <section className="relative overflow-hidden px-5 pb-16 pt-12 sm:px-8 lg:px-12 lg:pb-24 lg:pt-20">
                    <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.02fr_.98fr] lg:gap-20">
                        <div className="relative z-10">
                            <div className="mb-7 inline-flex items-center gap-2 rounded-full bg-[#edf8fc] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-[#1e91ba]"><Sparkles size={13} /> Ruang baca SMANSA</div>
                            <h1 className="max-w-xl font-display text-[clamp(3.2rem,7vw,6.6rem)] font-black leading-[.9] tracking-[-.065em] text-[#152235]">Temukan buku<br /><span className="text-[#159ac4]">favoritmu</span><br />hari ini.</h1>
                            <p className="mt-7 max-w-md text-sm leading-7 text-[#687580]">Jelajahi koleksi Perpustakaan SMAN 1 Bukittinggi. Baca, temukan ide baru, dan tumbuh bersama pengetahuan.</p>
                            <form action="/catalog" method="get" className="mt-8 flex max-w-lg items-center gap-2 rounded-2xl border border-[#e5e9e8] bg-white p-2 shadow-[0_15px_35px_-25px_rgba(21,77,100,.45)] focus-within:border-[#159ac4] focus-within:ring-4 focus-within:ring-[#159ac4]/10">
                                <Search size={18} className="ml-3 shrink-0 text-[#8b9ba4]" /><input name="q" aria-label="Cari buku" placeholder="Cari judul, penulis, atau kategori..." className="min-w-0 flex-1 border-0 bg-transparent px-2 py-3 text-xs text-[#172334] outline-none placeholder:text-[#a9b4b8]" /><button className="rounded-xl bg-[#159ac4] px-5 py-3 text-xs font-bold text-white shadow-sm hover:bg-[#117fa3]">Cari</button>
                            </form>
                            <div className="mt-8 flex flex-wrap gap-7 text-[11px] text-[#71808a]"><span><strong className="mr-1 text-xl font-black text-[#172334]">{stats.total_books || 0}</strong> koleksi buku</span><span><strong className="mr-1 text-xl font-black text-[#172334]">{stats.total_categories || 0}</strong> kategori</span><span><strong className="mr-1 text-xl font-black text-[#172334]">{stats.available_books || 0}</strong> siap dibaca</span></div>
                        </div>
                        <div className="relative min-h-[360px] lg:min-h-[500px]"><div className="absolute right-4 top-2 h-16 w-16 rounded-full border border-[#f0d56d] lg:right-16" /><div className="absolute left-0 top-14 h-72 w-72 rounded-[48%] bg-[#f9d34f] lg:left-8 lg:h-[390px] lg:w-[390px]" /><div className="absolute bottom-2 right-0 h-64 w-64 rounded-[48%] bg-[#f4a56b] lg:right-8 lg:h-[350px] lg:w-[350px]" /><img src="/images/hero_library.jpg" alt="Ruang baca perpustakaan" className="absolute left-3 top-16 z-10 h-64 w-52 rotate-[-6deg] rounded-[30px] object-cover shadow-[0_25px_40px_-20px_rgba(35,50,60,.55)] lg:left-12 lg:top-24 lg:h-[350px] lg:w-[285px]" /><img src="/images/about_building.jpg" alt="Perpustakaan SMANSA" className="absolute bottom-8 right-2 z-20 h-52 w-44 rotate-[7deg] rounded-[28px] border-8 border-white object-cover shadow-[0_25px_40px_-20px_rgba(35,50,60,.55)] lg:bottom-4 lg:right-16 lg:h-[290px] lg:w-[240px]" /><div className="absolute bottom-0 left-2 z-30 rounded-2xl bg-white px-4 py-3 shadow-lg lg:left-0"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#159ac4]">Open for everyone</p><p className="mt-1 text-xs font-bold text-[#172334]">Baca lebih banyak, tumbuh lebih jauh.</p></div></div>
                    </div>
                </section>

                <section className="border-y border-[#edf0ee] bg-[#fbfcfa] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#159ac4]">Semua ada di satu tempat</p><h2 className="mt-3 max-w-sm font-display text-4xl font-black leading-[.98] tracking-[-.045em] text-[#172334] sm:text-5xl">Satu ruang untuk semua rasa ingin tahu.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-[#71808a]">Mulai dari buku pelajaran, bacaan ringan, sampai karya warga sekolah—semuanya mudah ditemukan di sini.</p><ul className="mt-6 grid gap-3 text-xs font-semibold text-[#44535d]"><li>✓ Koleksi terkurasi untuk warga sekolah</li><li>✓ Reservasi buku tanpa antre panjang</li><li>✓ Akses majalah digital pilihan</li></ul><Link href="/information" className="mt-7 inline-flex items-center gap-2 text-xs font-bold text-[#159ac4]">Lihat semua fitur <ArrowRight size={14} /></Link></div><div className="grid gap-4 sm:grid-cols-3">{featureCards.map((card) => <Link key={card.href} href={card.href} className={`${card.color} group rounded-[26px] p-5 shadow-[0_18px_30px_-25px_rgba(34,54,64,.45)] transition hover:-translate-y-2`}><div className="flex h-28 items-end justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-white/75 text-2xl text-[#159ac4] shadow-sm">{card.icon}</span><ArrowRight size={17} className="text-[#60727b] transition group-hover:translate-x-1" /></div><p className="mt-5 text-[9px] font-bold uppercase tracking-[.16em] text-[#71808a]">{card.eyebrow}</p><h3 className="mt-1 font-display text-xl font-black leading-tight text-[#172334]">{card.title}</h3><p className="mt-2 text-xs leading-5 text-[#71808a]">{card.description}</p><span className="mt-5 inline-flex rounded-full border border-[#159ac4]/40 px-3 py-1.5 text-[10px] font-bold text-[#159ac4]">Buka</span></Link>)}</div></div></section>

                <section className="px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#159ac4]">Pilihan pembaca</p><h2 className="mt-2 font-display text-3xl font-black tracking-[-.04em] text-[#172334] sm:text-4xl">Buku terbaru</h2></div><Link href="/catalog" className="hidden items-center gap-1 text-xs font-bold text-[#159ac4] sm:flex">Lihat semua <ArrowRight size={14} /></Link></div><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{popularBooks?.slice(0, 5).map((book) => <BookCard key={book.id} book={book} hasClip={false} />)}</div>{(!popularBooks || popularBooks.length === 0) && <p className="mt-8 rounded-2xl bg-[#f4f8f7] p-8 text-center text-sm text-[#71808a]">Koleksi buku akan segera hadir.</p>}<div className="mt-7 flex justify-end gap-2"><button aria-label="Buku sebelumnya" className="grid size-9 place-items-center rounded-full border border-[#dce5e5] text-[#71808a]"><ChevronLeft size={15} /></button><button aria-label="Buku berikutnya" className="grid size-9 place-items-center rounded-full border border-[#dce5e5] text-[#71808a]"><ChevronRight size={15} /></button></div></div></section>

                <section className="bg-[#f4f8f7] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#159ac4]">Bacaan digital</p><h2 className="mt-2 font-display text-3xl font-black tracking-[-.04em] text-[#172334] sm:text-4xl">E-Magazine terbaru</h2></div><Link href="/magazines" className="hidden items-center gap-1 text-xs font-bold text-[#159ac4] sm:flex">Lihat semua <ArrowRight size={14} /></Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{latestMagazines?.map((edition) => <Link key={edition.id} href={`/magazines/${edition.magazine?.slug ?? edition.magazine_id}`} className="group flex gap-4 rounded-2xl bg-white p-3 shadow-[0_15px_30px_-25px_rgba(34,54,64,.5)]"><div className="h-36 w-28 shrink-0 overflow-hidden rounded-xl bg-[#edf1ef]"><img src={edition.cover_image || '/images/hero_library.jpg'} alt={edition.edition_title} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /></div><div className="py-2"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#159ac4]">Edisi {edition.edition_number}</p><h3 className="mt-2 font-display text-xl font-black leading-tight text-[#172334]">{edition.edition_title}</h3><p className="mt-2 text-xs leading-5 text-[#71808a]">{edition.description || 'Temukan cerita dan wawasan terbaru dari ruang baca kami.'}</p><span className="mt-4 inline-flex items-center gap-1 text-[10px] font-bold text-[#159ac4]">Baca edisi <ArrowRight size={12} /></span></div></Link>)}</div>{(!latestMagazines || latestMagazines.length === 0) && <p className="mt-8 rounded-2xl bg-white p-8 text-center text-sm text-[#71808a]">Majalah digital akan segera hadir.</p>}</div></section>

                <section className="px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-8 rounded-[32px] bg-[#142c43] px-7 py-10 text-center text-white sm:px-12 lg:flex-row lg:text-left"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#f4d35e]">Mulai perjalanan membaca</p><h2 className="mt-3 max-w-xl font-display text-3xl font-black leading-tight sm:text-4xl">Sudah siap menemukan buku berikutnya?</h2><p className="mt-3 max-w-lg text-sm leading-6 text-blue-100">Koleksi baru menunggumu. Cari buku, simpan favorit, dan reservasi dengan mudah.</p></div><Link href="/catalog" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-[#159ac4] px-6 py-3.5 text-xs font-bold text-white hover:bg-[#38afd0]">Cari buku sekarang <ArrowRight size={15} /></Link></div></section>
            </div>
        </SiteShell>
    );
}
