import { Filter, Search, SlidersHorizontal, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useListBooks } from '@workspace/api-client-react';
import { Link, useLocation } from 'wouter';
import { BookCard } from '@/components/book-card';
import { CardSkeleton, EmptyState, QueryError } from '@/components/feedback';

export default function Catalog() {
  const [location, setLocation] = useLocation();
  const initial = useMemo(() => new URLSearchParams(location.split('?')[1] ?? ''), [location]);
  const [search, setSearch] = useState(initial.get('q') ?? '');
  const [category, setCategory] = useState(initial.get('category') ?? '');
  const [status, setStatus] = useState<'all' | 'available' | 'borrowed'>('all');
  const [sort, setSort] = useState<'popular' | 'newest'>('popular');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const params = useMemo(() => ({ q: search.trim() || undefined, category: category || undefined, status, sort }), [search, category, status, sort]);
  const query = useListBooks(params);
  const books = query.data ?? [];
  const categories = useMemo(() => Array.from(new Set(books.map((book) => book.category))).sort(), [books]);
  const clear = () => { setSearch(''); setCategory(''); setStatus('all'); setSort('popular'); setLocation('/catalog'); };
  return <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-10 lg:py-16">
    <div className="flex flex-col justify-between gap-5 border-b border-border pb-10 sm:flex-row sm:items-end"><div><p className="font-mono-display text-[10px] font-bold uppercase tracking-[.2em] text-primary">Katalog perpustakaan</p><h1 className="mt-3 font-display text-4xl font-bold tracking-tight sm:text-5xl">Cari bacaanmu.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Telusuri koleksi yang kami rawat untuk menemani pelajaran, rasa ingin tahu, dan waktu luang.</p></div><Link href="/" data-testid="link-catalog-home" className="text-sm font-bold text-primary hover:underline">Kembali ke beranda</Link></div>
    <div className="mt-8 flex flex-col gap-3 lg:flex-row"><div className="flex flex-1 items-center rounded-xl border border-input bg-card px-3 focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/10"><Search size={18} className="text-primary" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari judul atau nama penulis…" className="min-w-0 flex-1 bg-transparent px-3 py-3.5 text-sm outline-none" data-testid="input-catalog-search" />{search && <button type="button" onClick={() => setSearch('')} aria-label="Hapus pencarian" data-testid="button-clear-search" className="p-1 text-muted-foreground"><X size={16} /></button>}</div><button type="button" onClick={() => setFiltersOpen((open) => !open)} data-testid="button-toggle-filters" className="flex items-center justify-center gap-2 rounded-xl border border-input bg-card px-5 py-3 text-sm font-semibold lg:hidden"><SlidersHorizontal size={16} /> Filter koleksi</button><div className={`${filtersOpen ? 'grid' : 'hidden'} gap-3 rounded-xl border border-border bg-card p-3 sm:grid-cols-3 lg:flex lg:border-0 lg:bg-transparent lg:p-0`}><select value={category} onChange={(event) => setCategory(event.target.value)} data-testid="select-category" className="rounded-xl border border-input bg-card px-4 py-3 text-sm font-semibold outline-none focus:border-primary"><option value="">Semua kategori</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} data-testid="select-status" className="rounded-xl border border-input bg-card px-4 py-3 text-sm font-semibold outline-none focus:border-primary"><option value="all">Semua status</option><option value="available">Tersedia</option><option value="borrowed">Sedang dipinjam</option></select><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} data-testid="select-sort" className="rounded-xl border border-input bg-card px-4 py-3 text-sm font-semibold outline-none focus:border-primary"><option value="popular">Paling populer</option><option value="newest">Terbaru</option></select></div></div>
    <div className="mt-10 flex items-center justify-between"><p className="flex items-center gap-2 text-sm text-muted-foreground"><Filter size={14} className="text-primary" /> {query.isLoading ? 'Menyiapkan rak…' : `${books.length} buku ditemukan`}</p>{(search || category || status !== 'all' || sort !== 'popular') && <button type="button" onClick={clear} data-testid="button-reset-filters" className="text-xs font-bold text-primary hover:underline">Reset filter</button>}</div>
    <div className="mt-5">{query.isError ? <QueryError onRetry={() => query.refetch()} /> : query.isLoading ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{[1, 2, 3, 4, 5, 6, 7, 8].map((item) => <CardSkeleton key={item} />)}</div> : books.length ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{books.map((book) => <BookCard key={book.id} book={book} />)}</div> : <EmptyState title="Rak ini belum menemukan apa-apa" description="Coba kata kunci atau kategori lain. Semua buku kami punya cerita untuk dimulai." />}</div>
  </div>;
}