import { ArrowRight, BookMarked, LibraryBig, Search, Sparkles, UsersRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useGetLibraryStats, useListBooks, useListMagazines } from '@workspace/api-client-react';
import { Link, useLocation } from 'wouter';
import { BookCard } from '@/components/book-card';
import { CardSkeleton, EmptyState, QueryError } from '@/components/feedback';

export default function Home() {
  const [, setLocation] = useLocation();
  const [query, setQuery] = useState('');
  const statsQuery = useGetLibraryStats();
  const booksQuery = useListBooks({ sort: 'newest' });
  const magazinesQuery = useListMagazines();
  const books = booksQuery.data ?? [];
  const magazines = magazinesQuery.data ?? [];
  const categories = useMemo(() => Array.from(new Set(books.map((book) => book.category))).slice(0, 4), [books]);
  const statItems: Array<{ label: string; value: number | undefined; Icon: typeof LibraryBig }> = [
    { label: 'Koleksi buku', value: statsQuery.data?.totalBooks, Icon: LibraryBig },
    { label: 'Penulis', value: statsQuery.data?.totalAuthors, Icon: UsersRound },
    { label: 'Kategori', value: statsQuery.data?.totalCategories, Icon: BookMarked },
    { label: 'Siap dipinjam', value: statsQuery.data?.availableBooks, Icon: Sparkles },
  ];
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); setLocation(`/catalog${query.trim() ? `?q=${encodeURIComponent(query.trim())}` : ''}`); };

  return <div>
    <section className="relative overflow-hidden border-b border-border bg-primary text-primary-foreground">
      <div className="absolute -right-28 -top-32 size-[420px] rounded-full border-[54px] border-accent/25" /><div className="absolute -bottom-36 left-[46%] size-[300px] rounded-full border-[40px] border-primary-foreground/10" /><div className="absolute inset-0 opacity-10 paper-grid" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 md:grid-cols-[1.1fr_.9fr] md:py-28 lg:px-10 lg:py-32">
        <div className="fade-up"><p className="font-mono-display text-[11px] font-bold uppercase tracking-[.2em] text-accent">Digital Library · SMAN 1 Bukittinggi</p><h1 className="mt-6 max-w-2xl font-display text-5xl font-bold leading-[1.02] tracking-[-.04em] sm:text-6xl lg:text-[76px]">Temukan halaman yang <span className="text-accent">menunggumu.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-primary-foreground/75 sm:text-lg">Koleksi buku, majalah, dan cerita dari perpustakaan sekolah — terbuka untuk siapa pun yang ingin tahu lebih banyak.</p><form onSubmit={submitSearch} className="mt-9 flex max-w-xl items-center rounded-2xl bg-card p-1.5 text-foreground shadow-xl"><Search size={19} className="ml-3 shrink-0 text-primary" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari judul, penulis, atau topik…" className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none" data-testid="input-home-search" /><button type="submit" data-testid="button-home-search" className="rounded-xl bg-accent px-4 py-3 text-sm font-bold text-accent-foreground transition hover:brightness-105">Cari</button></form><div className="mt-5 flex items-center gap-2 text-xs text-primary-foreground/60"><Sparkles size={13} className="text-accent" /> Mulai dari satu buku. Lihat ke mana ia membawamu.</div></div>
        <div className="relative hidden min-h-[360px] md:block fade-up-delay"><div className="absolute left-8 top-14 h-64 w-48 rotate-[-8deg] rounded-sm bg-accent p-4 shadow-2xl"><div className="flex h-full flex-col justify-between border border-accent-foreground/30 p-4 text-accent-foreground"><BookMarked size={26} /><div><p className="font-mono-display text-[9px] uppercase tracking-widest">Catatan baca</p><p className="mt-3 font-display text-3xl font-bold leading-none">Baca<br />perlahan.</p></div><p className="font-mono-display text-[9px]">01 / 2024</p></div></div><div className="absolute right-8 top-4 h-72 w-52 rotate-[8deg] rounded-sm bg-card p-4 text-foreground shadow-2xl"><div className="flex h-full flex-col justify-between border border-primary/20 p-4"><p className="font-mono-display text-[9px] uppercase tracking-widest text-primary">Ruang baca</p><div><div className="mb-3 h-1 w-14 bg-accent" /><p className="font-display text-4xl font-bold leading-[.95]">Satu<br />bab lagi.</p></div><div className="flex justify-between text-[10px] text-muted-foreground"><span>SMANSA</span><span>BUKITTINGGI</span></div></div></div></div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-10"><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-4">{statItems.map(({ label, value, Icon }, index) => <div key={label} className="bg-card px-4 py-5 sm:px-6"><div className="flex items-center gap-2 text-muted-foreground"><Icon size={15} className="text-primary" /><span className="font-mono-display text-[10px] uppercase tracking-[.12em]">{label}</span></div>{statsQuery.isLoading ? <div className="skeleton mt-3 h-8 w-20 rounded" /> : <p className="mt-2 font-display text-3xl font-bold text-foreground" data-testid={`stat-${index}`}>{value ?? '—'}</p>}</div>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-10 sm:px-8 lg:px-10"><div className="flex items-end justify-between gap-5"><div><p className="font-mono-display text-[10px] font-bold uppercase tracking-[.18em] text-primary">Baru di rak</p><h2 className="ink-rule mt-3 font-display text-3xl font-bold sm:text-4xl">Buku pilihan minggu ini</h2></div><Link href="/catalog" data-testid="link-home-catalog" className="hidden items-center gap-2 text-sm font-bold text-primary transition hover:gap-3 sm:flex">Lihat semua <ArrowRight size={16} /></Link></div>{booksQuery.isError ? <div className="mt-10"><QueryError onRetry={() => booksQuery.refetch()} /></div> : <div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{booksQuery.isLoading ? [1, 2, 3, 4].map((item) => <CardSkeleton key={item} />) : books.length ? books.slice(0, 4).map((book) => <BookCard key={book.id} book={book} />) : <div className="col-span-full"><EmptyState /></div>}</div>}<Link href="/catalog" data-testid="link-home-catalog-mobile" className="mt-7 flex items-center justify-center gap-2 text-sm font-bold text-primary sm:hidden">Lihat semua koleksi <ArrowRight size={16} /></Link></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-8 rounded-3xl bg-secondary p-7 sm:p-10 md:grid-cols-[.9fr_1.1fr] md:items-center"><div><p className="font-mono-display text-[10px] font-bold uppercase tracking-[.18em] text-primary">Jelajah berdasarkan minat</p><h2 className="mt-3 font-display text-3xl font-bold leading-tight sm:text-4xl">Tidak tahu mulai dari mana?</h2><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">Pilih satu tema. Barangkali, buku yang kamu cari sedang menunggumu di sana.</p></div><div className="grid grid-cols-2 gap-3">{(categories.length ? categories : ['Fiksi', 'Sains', 'Sejarah', 'Seni']).map((category) => <Link key={category} href={`/catalog?category=${encodeURIComponent(category)}`} data-testid={`link-category-${category}`} className="group flex items-center justify-between rounded-xl border border-border/80 bg-card px-4 py-4 text-sm font-semibold transition hover:border-primary hover:text-primary"><span>{category}</span><ArrowRight size={15} className="text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></Link>)}</div></div></section>

    {magazines.length > 0 && <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:px-10"><div className="flex items-end justify-between"><div><p className="font-mono-display text-[10px] font-bold uppercase tracking-[.18em] text-primary">Terbitan digital</p><h2 className="mt-3 font-display text-3xl font-bold">Baca yang terbaru</h2></div><Link href="/magazines" data-testid="link-home-magazines" className="flex items-center gap-2 text-sm font-bold text-primary">Semua edisi <ArrowRight size={16} /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{magazines.slice(0, 3).map((magazine) => <Link key={magazine.id} href="/magazines" className="group flex gap-4 rounded-2xl border border-border bg-card p-3 transition hover-lift" data-testid={`card-magazine-home-${magazine.id}`}><img src={magazine.coverUrl} alt={`Sampul ${magazine.title}`} className="h-28 w-20 rounded-lg object-cover" /><div className="py-1"><p className="font-mono-display text-[10px] uppercase tracking-widest text-primary">{magazine.edition} · {magazine.year}</p><h3 className="mt-2 font-display text-lg font-bold leading-tight">{magazine.title}</h3><span className="mt-4 inline-block text-xs font-bold text-primary">Baca edisi →</span></div></Link>)}</div></section>}
  </div>;
}